{% set name = "pycron" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 114c71bc61002b850a416e33e72a8c6de75b9f5c4228e86d7babd8a7ea232d94

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.9,<3.13
    - pip
    - poetry-core
  run:
    - python >=3.9,<3.13

test:
  imports:
    - pycron
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/kipe/pycron
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple cron-like parser, which determines if current datetime matches conditions.'
  dev_url: https://github.com/kipe/pycron

extra:
  recipe-maintainers:
    - synapticarbors
