schema_version: 1

context:
  version: "3.3.0"

package:
  name: pycron
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pycron/pycron-${{ version }}.tar.gz
  sha256: 877017822a65b949713b4746dcd3a3ff5bbd8b26db55e20e472dc191ea539d69

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - uv-dynamic-versioning
  run:
    - python >=${{ python_min }},<4.0

tests:
  - python:
      imports:
        - pycron
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  license: MIT
  license_file: LICENSE
  summary: Simple cron-like parser, which determines if current datetime matches conditions.
  homepage: https://github.com/kipe/pycron
  repository: https://github.com/kipe/pycron

extra:
  recipe-maintainers:
    - synapticarbors
